version: '3.8'

services:
  # MySQL database service
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: your_wordpress_db_password
    networks:
      - wp_site

  # WordPress service
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    expose:
      - 80
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: your_wordpress_db_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - wp_site

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    expose:
      - 80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - wp_site
      - nginxproxymanager_default

  # Nginx service as reverse proxy
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - wp_site
      - nginxproxymanager_default

networks:
  wp_site:
  nginxproxymanager_default:
    external: true
volumes:
  db_data:
  wordpress_data:
